# Generated by Django 4.0.3 on 2022-08-03 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_alter_address_zipcode_alter_sales_automobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AutomobilesVO',
            new_name='AutomobileVO',
        ),
        migrations.RenameModel(
            old_name='Sales',
            new_name='Sale',
        ),
    ]
