# Generated by Django 4.0.3 on 2022-08-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_rename_automobilesvo_automobilevo_rename_sales_sale'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['state', 'city']},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
    ]
