# Generated by Django 4.0.3 on 2022-08-04 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0004_alter_address_options_alter_state_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
