# Generated by Django 4.0.3 on 2022-08-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0007_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesman',
            name='employee_id',
            field=models.IntegerField(unique=True),
        ),
    ]
