# Generated by Django 4.0.3 on 2022-08-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_alter_vehiclemodel_picture_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='automobile',
            options={'ordering': ['model', 'year', 'color']},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='vehiclemodel',
            options={'ordering': ['manufacturer', 'name']},
        ),
        migrations.AddField(
            model_name='automobile',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
