# Generated by Django 4.0.3 on 2022-08-03 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0003_alter_automobile_options_alter_manufacturer_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobile',
            name='sold',
        ),
    ]
